name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true

          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            nvm use 22

            cd /opt/github/abheepay-main-site

            git pull origin main

            npm install

            npm run build

            find /var/www/abheepay.com/ -mindepth 1 -delete

            cp -rv dist/* /var/www/abheepay.com/

            echo "Deployment completed successfully!"